### PR TITLE
Delay when emptying queue

### PR DESCRIPTION
**Pull request by CaEurogard**
Hi,
our mqtt broker is overloaded, when to many iot devices push their queues at the same time.
This is a very simple approach with default delay and configurable delay via msg.delay packet.

### CODE REVIEW

**Comment by damoclark** [comment]
Hi @CaEurogard 

Rather than implementing rate-limiting into this node, you can add a delay node downstream of it and set rate limiting there so your broker doesn't become overwhelmed.

**Comment by CaEurogard** [comment]
Hi Damo,

 

but my problem that I cannot determine if it is a packet from the queue or a live packet. Therefore all my packets would be send delayed.

 

 

 

Von: Damo <notifications@github.com> 
Gesendet: Donnerstag, 6. August 2020 14:27
An: damoclark/node-red-contrib-msg-queue <node-red-contrib-msg-queue@noreply.github.com>
Cc: CaEurogard <mario.cappello@eurogard.de>; Mention <mention@noreply.github.com>
Betreff: Re: [damoclark/node-red-contrib-msg-queue] Delay when emptying queue (#11)

 

Hi @CaEurogard <https://github.com/CaEurogard> 

Rather than implementing rate-limiting into this node, you can add a delay node downstream of it and set rate limiting there so your broker doesn't become overwhelmed.

**Comment by damoclark** [comment]
The delay node can do rate limiting, which will limit how much is sent over time.  This means it will only delay messages when the rate of transmission reaches a certain threshold.  If you have scalability issues with your broker, then you probably want to do rate limiting broadly anyway.

Take a look at the 'Rate Limit' mode on the node to see the limits you can enforce so as not to overwhelm your broker.

**Comment by CaEurogard** [comment]
OK, Thanks for the hint.
   
  
  
   Then my PR is dispensable.
   
  
  
   Damo <notifications@github.com> hat am 7. August 2020 um 03:59 geschrieben: 
   
   
   
   The delay node can do rate limiting, which will limit how much is sent over time. This means it will only delay messages when the rate of transmission reaches a certain threshold. If you have scalability issues with your broker, then you probably want to do rate limiting broadly anyway.
   Take a look at the 'Rate Limit' mode on the node to see the limits you can enforce so as not to overwhelm your broker.

**Comment by CaEurogard** [comment]
I checked the proposed way and it is working as expected.

 

But a big flaw is when the queue-node is decreasing and the internal queue of the delay node is increasing all persistent data is not persistent anymore.

 

So if you have a malfunction or power breakdown all the values in the delay node are lost whereas in the msg node they would be protected from loss.

 

Maybe you think of a butterfly valve at the output of msg node…

 

Von: Damo <notifications@github.com> 
Gesendet: Freitag, 7. August 2020 03:59
An: damoclark/node-red-contrib-msg-queue <node-red-contrib-msg-queue@noreply.github.com>
Cc: CaEurogard <mario.cappello@eurogard.de>; Mention <mention@noreply.github.com>
Betreff: Re: [damoclark/node-red-contrib-msg-queue] Delay when emptying queue (#11)

 

The delay node can do rate limiting, which will limit how much is sent over time. This means it will only delay messages when the rate of transmission reaches a certain threshold. If you have scalability issues with your broker, then you probably want to do rate limiting broadly anyway.

Take a look at the 'Rate Limit' mode on the node to see the limits you can enforce so as not to overwhelm your broker.

**Comment by CaEurogard** [comment]
Hello Damo,

 

just want to check, if you have read my last comment after closing my PR.

 

This function is essential for us. If you still decline the PR we have to use the fork in our production scenario what would not be my first choice….

 

BR,

 

CAEurogard

 

Von: Damo <notifications@github.com> 
Gesendet: Freitag, 7. August 2020 03:59
An: damoclark/node-red-contrib-msg-queue <node-red-contrib-msg-queue@noreply.github.com>
Cc: CaEurogard <mario.cappello@eurogard.de>; Mention <mention@noreply.github.com>
Betreff: Re: [damoclark/node-red-contrib-msg-queue] Delay when emptying queue (#11)

 

The delay node can do rate limiting, which will limit how much is sent over time. This means it will only delay messages when the rate of transmission reaches a certain threshold. If you have scalability issues with your broker, then you probably want to do rate limiting broadly anyway.

Take a look at the 'Rate Limit' mode on the node to see the limits you can enforce so as not to overwhelm your broker.

**Pull request closed without merging**
